---
title: "GNRS"
author: "Brian Maitner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NSR R package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Geographic Name Resolution Service

The package `GNRS` is designed to interact with the Geographic Name Resolution Service of the Botanical Information and Ecology Network.  


#Installing NSR
```{r, eval=FALSE}

library(devtools)
install_github("EnquistLab/RGNRS/GNRS")


```

#The easiest case: one political division

```{r}
library(GNRS)
GNRS_super_simple(country =  "United States", 
                 state_province = "Arizona",
                 county_parish = "Pima County")


```

#Multiple political divisions

```{r}

#First, we'll grab some occurrence records from BIEN
library(BIEN)
xs <- BIEN_occurrence_species(species = "Xanthium strumarium", political.boundaries = T)


#The GNRS function expects 4 columns as input, but all are optional.
#If you ever forget, you can use the function NSR_template as a quick lookup, or to populate.

xs_query<-NSR_template(nrow = nrow(xs))

xs_query$country <- xs$country
xs_query$state_province <- xs$state_province
xs_query$county_parish <- xs$county


xs_gnrs_results <- GNRS(xs_query)

head(xs_gnrs_results)

```
