# Generated from the upstream GNRS SQL by dev_notes/gen_rules.py.  Do not edit by
# hand: the lists are transcribed mechanically so that they cannot drift from
# sql/populate_sp_verbatim_alt.sql and sql/populate_cp_verbatim_alt.sql in
# https://github.com/ojalaquellueva/gnrs.

#' Rules stripping administrative-class words from a submitted state name
#'
#' Internal.  Transcribed mechanically from the upstream
#' \code{sql/populate_sp_verbatim_alt.sql}: three CASE blocks, applied in
#' order, each a first-match-wins list of an ILIKE test and the text that
#' \code{regexp_replace()} removes when it fires.
#' @keywords internal
#' @noRd
gnrs_state_alt_rules <- function() {
  list(
    prefix_article = data.frame(
      like = c(
        "Avtonomnyy Okrug%",
        "Autonomous District%",
        "Autonomous Region%",
        "Avtonomnaya Oblast'%",
        "Canton d'%",
        "Canton de%",
        "Canton du%",
        "Castello di%",
        "Commune de%",
        "Concelho dos%",
        "Concelho do%",
        "Concelho da%",
        "Concelho de%",
        "Departement de l'%",
        "Departamento del%",
        "Departamento de%",
        "Departament of%",
        "Departement de%",
        "Distrito Capital de%",
        "Distrito del%",
        "Distrito da%",
        "Distrito do%",
        "Distrito de%",
        "Estado de%",
        "Gouvernorat de%",
        "Ile du %",
        "Ile %",
        "Municipio Especial%",
        "Muhafazat '%",
        "Muhafazat ad %",
        "Muhafazat al %",
        "Muhafazat `%",
        "Muhafazat ash ",
        "Muhafazat as %",
        "Muhafazat at %",
        "Ostan-ef%",
        "Parish of%",
        "Prefecture de la%",
        "Prefecture de%",
        "Principality of%",
        "Province de l'%",
        "Province of%",
        "Provincia del%",
        "Provincia des %",
        "Provincia de%",
        "Province du%",
        "Province de%",
        "Qarku i%",
        "Region Metropolitana de%",
        "Regional District of%",
        "Regione Autonoma%",
        "Region del%",
        "Region du%",
        "Region de%",
        "State of%",
        "Sha'biyat al%",
        "Sha'biyat an%",
        "Sha'biyat az%",
        "Sha'biyat%",
        "Union Territory of%",
        "Wilayat-e%",
        "Wilaya du %",
        "Wilaya d'%",
        "Wilaya de%"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        "Avtonomnyy Okrug",
        "Autonomous District",
        "Autonomous Region",
        "Avtonomnaya Oblast'",
        "Canton d'",
        "Canton de",
        "Canton du",
        "Castello di",
        "Commune de",
        "Concelho dos",
        "Concelho do",
        "Concelho da",
        "Concelho de",
        "Departement de l'",
        "Departamento del",
        "Departamento de",
        "Departament of",
        "Departement de",
        "Distrito Capital de",
        "Distrito del",
        "Distrito da",
        "Distrito do",
        "Distrito de",
        "Estado de",
        "Gouvernorat de",
        "Ile du ",
        "Ile ",
        "Municipio Especial",
        "Muhafazat '",
        "Muhafazat ad ",
        "Muhafazat al ",
        "Muhafazat `",
        "Muhafazat ash ",
        "Muhafazat as ",
        "Muhafazat at ",
        "Ostan-e",
        "Parish of",
        "Prefecture de la",
        "Prefecture de",
        "Principality of",
        "Province de l'",
        "Province of",
        "Provincia del",
        "Provincia des ",
        "Provincia de",
        "Province du",
        "Province de",
        "Qarku i",
        "Region Metropolitana de",
        "Regional District of",
        "Regione Autonoma",
        "Region del",
        "Region du",
        "Region de",
        "State of",
        "Sha'biyat al",
        "Sha'biyat an",
        "Sha'biyat az",
        "Sha'biyat",
        "Union Territory of",
        "Wilayat-e",
        "Wilaya du ",
        "Wilaya d'",
        "Wilaya de"
      ),
      stringsAsFactors = FALSE
    ),
    prefix = data.frame(
      like = c(
        "Canton%",
        "Changwat%",
        "Kanton%",
        "Concelho%",
        "Departamento%",
        "Departament%",
        "Departement%",
        "Distrikt%",
        "Distrito%",
        "Eparchia%",
        "Estado%",
        "Gobolka%",
        "Gouvernorat%",
        "Judetul%",
        "Mohafazat%",
        "Muhafazat%",
        "Obcina%",
        "Oblast%",
        "Opstina%",
        "Parish%",
        "Prefecture%",
        "Principality%",
        "Provincie %",
        "Province%",
        "Provincia%",
        "Provinsi%",
        "Region%",
        "Raionul%",
        "Respublika%",
        "State%",
        "Tinh%",
        "Union Territory%",
        "Wilaya%",
        "Wojewodztwo%"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Distrito Capital%",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        "Canton",
        "Changwat",
        "Kanton",
        "Concelho",
        "Departamento",
        "Departament",
        "Departement",
        "Distrikt",
        "Distrito",
        "Eparchia",
        "Estado",
        "Gobolka",
        "Gouvernorat",
        "Judetul",
        "Mohafazat",
        "Muhafazat",
        "Obcina",
        "Oblast",
        "Opstina",
        "Parish",
        "Prefecture",
        "Principality",
        "Provincie ",
        "Province",
        "Provincia",
        "Provinsi",
        "Region",
        "Raionul",
        "Respublika",
        "State",
        "Tinh",
        "Union Territory",
        "Wilaya",
        "Wojewodztwo"
      ),
      stringsAsFactors = FALSE
    ),
    suffix = data.frame(
      like = c(
        "% County",
        "% Department",
        "% District",
        "% Division",
        "% Governorate",
        "% Marz",
        "% Municipality",
        "% Municipio",
        "% Novads",
        "% Parish",
        "% Oblast'",
        "% Oblast",
        "% Province",
        "% Rayon",
        "% Region",
        "% State",
        "% Territory"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        "County",
        "Department",
        "District",
        "Division",
        "Governorate",
        "Marz",
        "Municipality",
        "Municipio",
        "Novads",
        " Parish",
        " Oblast'",
        " Oblast",
        "Province",
        "Rayon",
        "Region",
        "State",
        "Territory"
      ),
      stringsAsFactors = FALSE
    )
  )
}

#' Rules stripping administrative-class words from a submitted county name
#'
#' Internal.  Transcribed mechanically from the upstream
#' \code{sql/populate_cp_verbatim_alt.sql}; see \code{gnrs_state_alt_rules()}.
#' @keywords internal
#' @noRd
gnrs_county_alt_rules <- function() {
  list(
    prefix_article = data.frame(
      like = c(
        "Arrondissement des%",
        "Arrondissement de%",
        "Arrondissement du%",
        "Borough of %",
        "Canton de%",
        "Castello di%",
        "Commune de%",
        "Concelho do%",
        "Concelho da%",
        "Concelho de%",
        "Circunscricao da %",
        "Circunscricao de %",
        "Circunscricao do %",
        "City and Borough of %",
        "City and County of%",
        "City of%",
        "Commune of%",
        "Delegation de %",
        "Delegation d'%",
        "Departement des %",
        "Departement du %",
        "Departement d'",
        "Departement de la %",
        "Departement de l'%",
        "Departamento del%",
        "Departamento de%",
        "Departament of%",
        "Departement de%",
        "Distrito del%",
        "Distrito da%",
        "Distrito do%",
        "Distrito de%",
        "Estado de%",
        "Gouvernorat de%",
        "Heroica Ciudad de %",
        "Heroica Villa de %",
        "Heroica Villa %",
        "Komuna e %",
        "Municipio Autonomo %",
        "Municipio de%",
        "Municipio Especial%",
        "Parish of%",
        "Partido de %",
        "Prefecture de la%",
        "Prefecture de%",
        "Principality of%",
        "Province of%",
        "Provincia del%",
        "Provincia de%",
        "Province du%",
        "Province de%",
        "Qada' al %",
        "Qada' ar %",
        "Qada' as %",
        "Qada' at %",
        "Qada' `%",
        "Regional District of %",
        "Qarku i%",
        "Region del%",
        "Region du %",
        "Region de %",
        "San Agustin del %",
        "San Agustin de %",
        "San Agustin %",
        "San Andres del %",
        "San Andres de %",
        "San Andres %",
        "San Antonino del %",
        "San Antonino de %",
        "San Antonino %",
        "San Antonino %",
        "San Baltazar %",
        "San Bartolo %",
        "San Bartolome %",
        "San Carlos Yautepec%",
        "San Cristobal de %",
        "San Damian %",
        "San Diego la Mesa %",
        "San Diego de %",
        "San Diego %",
        "San Dionisio del %",
        "San Dionisio %",
        "San Felipe del %",
        "San Felipe de %",
        "San Felipe %",
        "San Francisco del %",
        "San Francisco de %",
        "San Francisco %",
        "San Gabriel %",
        "San Gregorio De %",
        "San Gregorio %",
        "San Ignacio de %",
        "San Ignacio %",
        "San Ildefonso %",
        "San Isidro %",
        "San Jeronimo %",
        "San Jose del %",
        "San Jose de %",
        "San Jose %",
        "San Juan Bautista %",
        "San Juan del %",
        "San Juan de %",
        "San Juan %",
        "San Lorenzo %",
        "San Lucas %",
        "San Luis del %",
        "San Luis de %",
        "San Luis %",
        "San Manuel de %",
        "San Manuel %",
        "San Marcial %",
        "San Martin de %",
        "San Martin ",
        "San Mateo del %",
        "San Mateo de %",
        "San Mateo %",
        "San Matias %",
        "San Melchor %",
        "xxSan Miguel del x%",
        "San Miguel de %",
        "San Miguel %",
        "San Nicolas de %",
        "San Nicolas %",
        "San Pablo del %",
        "San Pablo de %",
        "San Pablo %",
        "San Patricio %",
        "San Pedro del %",
        "San Pedro de %",
        "San Pedro %",
        "San Pedro y San Pablo %",
        "San Rafael del %",
        "San Raymundo %",
        "San Salvador %",
        "San Sebastian de %",
        "San Sebastian %",
        "San Simon de %",
        "San Simon %",
        "Santa Ana de %",
        "Santa Ana %",
        "Santa Apolonia %",
        "Santa Barbara de %",
        "Santa Barbara Do %",
        "Santa Barbara Do %",
        "Santa Catalina %",
        "Santa Catarina %",
        "Santa Cruz Da %",
        "Santa Cruz Das %",
        "Santa Cruz de %",
        "Santa Cruz %",
        "Santafe de Antioquia%",
        "Santa Fe De %",
        "Santa Fe Do %",
        "Santa Fe %",
        "Santa Filomena Do %",
        "Santa Helena De %",
        "Santa Ines de %",
        "Santa Ines %",
        "Santa Isabel Do %",
        "Santa Isabel %",
        "Santa Lucia %",
        "Santa Luzia do %",
        "Santa Luzia %",
        "Santa Magdalena %",
        "Santa Maria Das %",
        "Santa Maria da %",
        "Santa Maria del %",
        "Santa Maria Do %",
        "Santa Maria %",
        "Santana Da %",
        "Santana De %",
        "Santana Do %",
        "Santana Dos %",
        "Santander de %",
        "Santa Rita De %",
        "Santa Rita Do %",
        "Santa Rosa de %",
        "Santa Rosa Da %",
        "Santa Tereza De %",
        "Santa Tereza Do %",
        "Santa Terezinha De %",
        "Santa Vitoria Do %",
        "Santiago de %",
        "Santiago do %",
        "Santiago %",
        "Santo Amaro Das %",
        "Santo Amaro Da %",
        "Santo Amaro Do %",
        "Santo Antonio Das %",
        "Santo Antonio Da %",
        "Santo Antonio De %",
        "Santo Antonio Do %",
        "Santo Domingo %",
        "Santo Inacio Do %",
        "Santos Reyes %",
        "San Vicente del %",
        "San Vicente de %",
        "San Vicente %",
        "Sao Benedito Do Rio Preto%",
        "Sao Bento De %",
        "Sao Bento Do %",
        "Sao Bras de %",
        "Sao Braz Do %",
        "Sao Caetano De Odivela%",
        "Sao Carlos Do Iva%",
        "Sao Domingos Das %",
        "Sao Domingos Do %",
        "Sao Felix De %",
        "Sao Felix Do %",
        "Sao Francisco De %",
        "Sao Gabriel Da %",
        "Sao Geraldo Da %",
        "Sao Geraldo Do %",
        "Sao Goncalo Do %",
        "Sao Goncalo %",
        "Sao Joao Da %",
        "Sao Joao Das %",
        "Sao Joao D'%",
        "Sao Joao De %",
        "Sao Joao Do %",
        "Sao Joao %",
        "Sao Joaquim Da %",
        "Sao Jorge Do %",
        "Sao Jose Da %",
        "Sao Jose Das %",
        "Sao Jose De %",
        "Sao Jose Do %",
        "Sao Lourenco Da %",
        "Sao Lourenco do %",
        "Sao Luis De %",
        "Sao Luis Do %",
        "Sao Luis Gonzaga Do %",
        "Sao Luiz Gonzaga%",
        "Sao Manoel Do %",
        "Sao Mateus Do Maranhao%",
        "Sao Miguel da %",
        "Sao Miguel Das %",
        "Sao Miguel De %",
        "Sao Miguel Do %",
        "Sao Miguel Dos %",
        "Sao Paulo Das %",
        "Sao Paulo De %",
        "Sao Paulo Do %",
        "Sao Pedro Da %",
        "Sao Pedro Das %",
        "Sao Pedro Do %",
        "Sao Pedro dos %",
        "Sao Raimundo Das %",
        "Sao Raimundo Do %",
        "Sao Raimundo %",
        "Sao Roque De %",
        "Sao Roque do %",
        "Sao Salvador Do %",
        "Sao Sebastiao Da %",
        "Sao Sebastiao De %",
        "Sao Sebastiao Do %",
        "Sao Vicente De Minas%",
        "Tamazulapam del Espiritu Santo%",
        "Villa de San Diego de %",
        "Villa de %",
        "Ville de %",
        "Wahlkreis %",
        "Ward of %",
        "State of %",
        "Union Territory of %",
        "Wilaya de %"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        "Arrondissement des",
        "Arrondissement de",
        "Arrondissement du",
        "Borough of ",
        "Canton de",
        "Castello di",
        "Commune de",
        "Concelho do",
        "Concelho da",
        "Concelho de",
        "Circunscricao da ",
        "Circunscricao de ",
        "Circunscricao do ",
        "City and Borough of ",
        "City and County of",
        "City of",
        "Commune of",
        "Delegation de ",
        "Delegation d'",
        "Departement des ",
        "Departement du ",
        "Departement d'",
        "Departement de la ",
        "Departement de l'",
        "Departamento del",
        "Departamento de",
        "Departament of",
        "Departement de",
        "Distrito del",
        "Distrito da",
        "Distrito do",
        "Distrito de",
        "Estado de",
        "Gouvernorat de",
        "Heroica Ciudad de ",
        "Heroica Villa de ",
        "Heroica Villa ",
        "Komuna e ",
        "Municipio Autonomo ",
        "Municipio de",
        "Municipio Especial",
        "Parish of",
        "Partido de ",
        "Prefecture de la",
        "Prefecture de",
        "Principality of",
        "Province of",
        "Provincia del",
        "Provincia de",
        "Province du",
        "Province de",
        "Qada' al ",
        "Qada' ar ",
        "Qada' as ",
        "Qada' at ",
        "Qada' `",
        "Regional District of ",
        "Qarku i",
        "Region del",
        "Region du ",
        "Region de ",
        "San Agustin del ",
        "San Agustin de ",
        "San Agustin ",
        "San Andres del ",
        "San Andres  ",
        "San Andres ",
        "San Antonino del ",
        "San Antonino ",
        "xxx",
        "San Antonino ",
        "San Baltazar ",
        "San Bartolo ",
        "San Bartolome ",
        "Yautepec",
        "San Cristobal de ",
        "San Damian ",
        "San Diego la Mesa ",
        "San Diego de ",
        "San Diego ",
        "San Dionisio del ",
        "San Dionisio ",
        "San Felipe del ",
        "San Felipe de ",
        "San Felipe ",
        "San Francisco del ",
        "San Francisco de ",
        "San Francisco ",
        "San Gabriel ",
        "San Gregorio De ",
        "San Gregorio ",
        "San Ignacio de ",
        "San Ignacio ",
        "San Ildefonso ",
        "San Isidro ",
        "San Jeronimo ",
        "San Jose del ",
        "San Jose de ",
        "San Jose ",
        "San Juan Bautista ",
        "San Juan del ",
        "San Juan de ",
        "San Juan ",
        "San Lorenzo ",
        "San Lucas ",
        "San Luis del ",
        "San Luis de ",
        "San Luis ",
        "San Manuel de ",
        "San Manuel ",
        "San Marcial ",
        "San Martin de ",
        "San Martin ",
        "San Mateo del ",
        "San Mateo de ",
        "San Mateo ",
        "San Matias ",
        "San Melchor ",
        "San Miguel del ",
        "San Miguel de ",
        "San Miguel ",
        "San Nicolas de ",
        "San Nicolas ",
        "San Pablo del ",
        "San Pablo de ",
        "San Pablo ",
        "San Patricio ",
        "San Pedro del ",
        "San Pedro de ",
        "San Pedro ",
        "San Pedro y San Pablo ",
        "San Rafael del ",
        "San Raymundo ",
        "San Salvador ",
        "San Sebastian de ",
        "San Sebastian ",
        "San Simon de ",
        "San Simon ",
        "Santa Ana de ",
        "Santa Ana ",
        "Santa Apolonia ",
        "Santa Barbara de ",
        "xxx",
        "xxx",
        "Santa Catalina ",
        "Santa Catarina ",
        "Santa Cruz Da ",
        "Santa Cruz Das ",
        "Santa Cruz de ",
        "Santa Cruz ",
        "Santafe de ",
        "Santa Fe De ",
        "Santa Fe Do ",
        "Santa Fe ",
        "Santa Filomena Do ",
        "Santa Helena De ",
        "Santa Ines de ",
        "Santa Ines ",
        "Santa Isabel Do ",
        "Santa Isabel ",
        "Santa Lucia ",
        "Santa Luzia do ",
        "Santa Luzia ",
        "Santa Magdalena ",
        "Santa Maria Das ",
        "Santa Maria da ",
        "Santa Maria del ",
        "Santa Maria Do ",
        "Santa Maria ",
        "Santana Da ",
        "Santana De ",
        "Santana Do ",
        "Santana Dos ",
        "Santander de ",
        "Santa Rita De ",
        "Santa Rita Do ",
        "Santa Rosa de ",
        "Santa Rosa Da ",
        "Santa Tereza De ",
        "Santa Tereza Do ",
        "Santa Terezinha De ",
        "Santa Vitoria Do ",
        "Santiago de ",
        "Santiago do ",
        "Santiago ",
        "Santo Amaro Das ",
        "Santo Amaro Da ",
        "Santo Amaro Do ",
        "Santo Antonio Das ",
        "Santo Antonio Da ",
        "Santo Antonio De ",
        "Santo Antonio Do ",
        "Santo Domingo ",
        "Santo Inacio Do ",
        "Santos Reyes ",
        "San Vicente del ",
        "San Vicente de ",
        "San Vicente ",
        "Sao Benedito Do ",
        "Sao Bento De ",
        "Sao Bento Do ",
        "Sao Bras de ",
        "Sao Braz Do ",
        "Sao Caetano De ",
        "Sao Carlos Do ",
        "Sao Domingos Das ",
        "Sao Domingos Do ",
        "Sao Felix De ",
        "Sao Felix Do ",
        "Sao Francisco De ",
        "Sao Gabriel Da ",
        "Sao Geraldo Da ",
        "Sao Geraldo Do ",
        "Sao Goncalo Do ",
        "Sao Goncalo ",
        "Sao Joao Da ",
        "Sao Joao Das ",
        "Sao Joao D'",
        "Sao Joao De ",
        "Sao Joao Do ",
        "Sao Joao ",
        "Sao Joaquim Da ",
        "Sao Jorge Do ",
        "Sao Jose Da ",
        "Sao Jose Das ",
        "Sao Jose De ",
        "Sao Jose Do ",
        "Sao Lourenco Da ",
        "Sao Lourenco do ",
        "Sao Luis De ",
        "Sao Luis Do ",
        "Sao Luis Gonzaga Do ",
        "Sao Luiz ",
        "Sao Manoel Do ",
        "Sao Mateus Do ",
        "Sao Miguel da ",
        "Sao Miguel Das ",
        "Sao Miguel De ",
        "Sao Miguel Do ",
        "Sao Miguel Dos ",
        "Sao Paulo Das ",
        "Sao Paulo De ",
        "Sao Paulo Do ",
        "Sao Pedro Da ",
        "Sao Pedro Das ",
        "Sao Pedro Do ",
        "Sao Pedro dos ",
        "Sao Raimundo Das ",
        "Sao Raimundo Do ",
        "Sao Raimundo ",
        "Sao Roque De ",
        "Sao Roque do ",
        "Sao Salvador Do ",
        "Sao Sebastiao Da ",
        "Sao Sebastiao De ",
        "Sao Sebastiao Do ",
        "Sao Vicente De ",
        " del Espiritu Santo",
        "Villa de San Diego de ",
        "Villa de ",
        "Ville de ",
        "Wahlkreis ",
        "Ward of ",
        "State of ",
        "Union Territory of ",
        "Wilaya de "
      ),
      stringsAsFactors = FALSE
    ),
    prefix = data.frame(
      like = c(
        "Amphoe%",
        "Arrondissement %",
        "Bashkia%",
        "Bezirk%",
        "Canton%",
        "Concelho%",
        "Changwat%",
        "Circunscricao%",
        "County %",
        "Comuna %",
        "Departamento%",
        "Departament%",
        "Departement%",
        "Distrito%",
        "Estado%",
        "Gemeente %",
        "Gorod %",
        "Gorodskoy okrug %",
        "Gouvernorat%",
        "Grad %",
        "Horad %",
        "Huyen %",
        "Kanton%",
        "Kabupaten %",
        "Kota Administrasi Jakarta %",
        "Kota %",
        "Liwa' %",
        "Markaz %",
        "Muang %",
        "Mudiriyat %",
        "Municipio %",
        "Municipiul %",
        "Nohiyai %",
        "Nomarchia %",
        "Nomos %",
        "Obcina%",
        "Obshtina %",
        "Opstina %",
        "Okres %",
        "Oras %",
        "Parish%",
        "Politischer Bezirk %",
        "Powiat %",
        "Prefecture %",
        "Principality%",
        "Province%",
        "Provincia%",
        "Provinsi%",
        "Qada' %",
        "Qeza-i %",
        "Quan %",
        "Region %",
        "Regierungsbezirk %",
        "Rrethi i %",
        "State %",
        "Shahrestan-e %",
        "Srok %",
        "Sveitarfelagid %",
        "Thanh Pho %",
        "Thi Xa %",
        "Union Territory%",
        "Wilaya%",
        "Tinh%"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        "Amphoe",
        "Arrondissement ",
        "Bashkia",
        "Bezirk",
        "Canton",
        "Concelho",
        "Changwat",
        "Circunscricao",
        "County ",
        "Comuna ",
        "Departamento",
        "Departament",
        "Departement",
        "Distrito",
        "Estado",
        "Gemeente ",
        "Gorod ",
        "Gorodskoy okrug ",
        "Gouvernorat",
        "Grad ",
        "Horad ",
        "Huyen ",
        "Kanton",
        "Kabupaten ",
        "Kota Administrasi Jakarta ",
        "Kota ",
        "Liwa' ",
        "Markaz ",
        "Muang ",
        "Mudiriyat ",
        "Municipio ",
        "Municipiul ",
        "Nohiyai ",
        "Nomarchia ",
        "Nomos ",
        "Obcina",
        "Obshtina ",
        "Opstina ",
        "Okres ",
        "Oras ",
        "Parish",
        "Politischer Bezirk ",
        "Powiat ",
        "Prefecture ",
        "Principality",
        "Province",
        "Provincia",
        "Provinsi",
        "Qada' ",
        "Qeza-i ",
        "Quan ",
        "Region ",
        "Regierungsbezirk ",
        "Rrethi i ",
        "State ",
        "Shahrestan-e ",
        "Srok ",
        "Sveitarfelagid ",
        "Thanh Pho ",
        "Thi Xa ",
        "Union Territory",
        "Wilaya",
        "Tinh"
      ),
      stringsAsFactors = FALSE
    ),
    suffix = data.frame(
      like = c(
        "%  Administrativnyy Okrug",
        "% Audany",
        "% District",
        "% County",
        "% Parish",
        "% Department",
        "% District",
        "% Division",
        "% Municipality",
        "% Munitsip'alit'et'i",
        "% Mis'krada",
        "% Municipio",
        "% Province",
        "% pagasts",
        "% Qalasy",
        "% Region",
        "% Rayon",
        "% Territory"
      ),
      not_like = c(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      replace = c(
        " Administrativnyy Okrug",
        " Audany",
        "District",
        " County",
        "Parish",
        " Department",
        " District",
        " Division",
        "Municipality",
        " Munitsip'alit'et'i",
        "Mis'krada",
        "Municipio",
        " Province",
        " pagasts",
        " Qalasy",
        " Region",
        " Rayon",
        "Territory"
      ),
      stringsAsFactors = FALSE
    )
  )
}
